data.json, script.js
I also added a `getString` function and made `langCode` a global constant
=> Add search bar

README.md, redirect.html
This PR adds a new page (`/redirect.html`), where it takes the parameter `r` in the URL which would be an `obtainium://` link, this would then redirect the user to the Obtainium app.
The URL would look like this: `http://apps.obtainium.imranr.dev/redirect.html?r=linkhere`
It will only redirect if the URL starts with `obtainium://add` (with valid JSON) or `obtainium://app` (with valid URL) to avoid this being used for malicious purposes.
The page will also display text with the link to the specified URL for the app, so that if the user does not have Obtainium installed, they can easily find a more suitable way to download the app.
=> Add Redirect Page

data.json
Cleaned up the Categories to remove some redundancies and not needed categories. There are a lot and I don't think we would benefit on having all of those. There probably is more that can be reduced but I took a conservative approach. 
- Added categories to some apps that weren't categorized.
Removed:
- Yuzu
- Citra
Added:
- Adaway
- UniPatcher
- KeyMapper
=> Cleaned up Categories, added and pruned apps

data.json
FFUpdater is an updater application for privacy friendly respecting browsers (such as Firefox which the name implies) and I think it's useful to list considering there have been a couple of threads on Obtainium side on how to install and update Firefox.
=> List FFUpdater

data/apps/com.secuso.privacyFriendlyCodeScanner.json
I'll stop spanning now. Promised!
=> Add QR Scanner (PFA).

data/apps/net.mullvad.mullvadvpn.json
=> Update Mullvad config

data/apps/app.titanius.launcher.json, data/apps/com.winlator.json
Hi,
I permit myself to correct the descriptions for Winator and Titanius Launcher apps. I also add an icon based on their android ic launcher.
=> Correct informations for Winator and Titanius Launcher

data/apps/at.bitfire.davdroid.json, data/apps/at.bitfire.icsdroid.json, data/apps/com.adguard.android.json, data/apps/com.geeksville.mesh.json, data/apps/com.ghisler.android.TotalCommander.json, data/apps/com.ghisler.tcplugins.FTP.json, data/apps/com.ghisler.tcplugins.LAN.json, data/apps/com.ghisler.tcplugins.SFTP.json, data/apps/com.ghisler.tcplugins.WebDAV.json, data/apps/com.ghisler.tcplugins.WindowsLive.json, data/apps/com.ghisler.tcplugins.drive.json, data/apps/com.ghisler.tcplugins.wifitransfer.json, data/apps/com.nextcloud.client.json, data/apps/com.termux.json, data/apps/de.blau.android.json, data/apps/de.kaffeemitkoffein.imagepipe.json, data/apps/eu.faircode.email.json, data/apps/helium314.keyboard.json, data/apps/keepass2android.keepass2android.json, data/apps/org.fossify.calendar.json, data/apps/org.fossify.contacts.json, data/apps/org.fossify.gallery.json, data/apps/org.handmadeideas.floccus.json, data/apps/org.joinmastodon.android.json, data/apps/org.schabi.newpipe.json, data/apps/org.y20k.transistor.json, data/apps/ru.tech.imageresizershrinker.json
Added several curated apps to the list. All repositories are actively developed and many of them, very popular.
=> Added apps

README.md
Add a link to the website to the README to make it more obvious that this project is a website.
Closes #30
=> Add website link to README

data/apps/app.lawnchair.debug.json, data/apps/app.mihon.json, data/apps/app.organicmaps.json, data/apps/at.techbee.jtx.json, data/apps/ch.ictrust.pobya.json, data/apps/com.adilhanney.saber.json, data/apps/com.aistra.hail.json, data/apps/com.artemchep.keyguard.json
I'm adding a few of the several apps I have made jsons from my obtainium export. Will contribute more once these are fine enough.
=> Add several apps

data/apps/com.meenbeese.chronos.json
I tested the change and it works fine. Please let me know if anything is wrong.
Thank you for creating an awesome app like Obtainium and a website to complement it.
=> Add Chronos as new app entry

data/style.css
I learned of this earlier today (sorry about not knowing to PR it with #68 😓 )  and I think it would be nice first try on Obtainium website for better integrating with Android. As older browsers/devices may not support it, I think the earlier added fallbacks are still necessary/useful though.
- https://caniuse.com/font-family-system-ui
=> style.css: attempt to use system ui font

data/strings.json, index.html, script.js
This PR adds a button to the home page with a link to request new apps on the discussions page:
=> Add Request Apps Button

index.html
The request apps button was only working when you clicked on the text, not around the text on the rest of the button.
=> Fix Request Apps Button

data/apps/at.bitfire.davdroid.json, data/apps/com.aurora.store.nightly.json
=> Fixing AuroraStore Nightly

data/apps/com.valvesoftware.steamlink.json
=> Fix Steam Link icon

generate_from_url.py
This PR includes a couple of improvements for the Python script
- Ensure there is a final new line. Fixes #129 
- Support adding additional files for apps with the same ID as already added apps in the rare cases this is needed
- Add reminders to users to add alt labels, icons, etc..
=> Python Script Improvements

data/apps/fe.linksheet.nightly.json
Adds [LinkSheet Nightly](https://github.com/LinkSheet/nightly), an app I'm working on
=> Add LinkSheet Nightly

data/apps/me.magnum.melonds.json
Adds melonDS stable and nightly
=> add melonDS

data/apps/io.github.lime3ds.android.json
=> add Lime3DS

data/apps/org.citra.emu.json
Adds 
- https://github.com/PabloMK7/citra
- https://github.com/CitraEnhanced/citra
- https://github.com/weihuoya/citra
=> add Citra forks

data/apps/io.github.pyoncord.manager.json
Adds:
- [Bunny Manager](https://github.com/pyoncord/BunnyManager)
=> add Bunny Manager

data/apps/ch.protonvpn.android.json, data/apps/com.gaurav.avnc.json, data/apps/com.github.gotify.json, data/apps/com.github.stenzek.duckstation.json, data/apps/com.jgeek00.droid_hole.json, data/apps/com.nononsenseapps.feeder.json, data/apps/com.seazon.feedme.json, data/apps/com.termux.api.json, data/apps/com.termux.boot.json, data/apps/com.termux.widget.json, data/apps/de.astubenbord.paperless_mobile.json, data/apps/de.luhmer.owncloudnewsreader.json, data/apps/dev.bartuzen.qbitcontroller.json, data/apps/eu.darken.sdmse.json, data/apps/fr.gaulupeau.apps.InThePoche.json, data/apps/fr.twentynine.keepon.json, data/apps/io.github.quillpad.json, data/apps/me.proton.android.calendar.json, data/apps/me.proton.android.drive.json, data/apps/moe.shizuku.privileged.api.json, data/apps/net.cozic.joplin.json
- Fixed the entries for Proton Calendar and Proton Drive
- Added 18 additional Android applications
=> Proton entries fixes & 18 additional Android applications

data/apps/com.adobe.lrmobile.json, data/apps/com.facebook.katana.json, data/apps/com.facebook.orca.json, data/apps/com.instagram.android.json, data/apps/com.reddit.frontpage.json, data/apps/io.ente.auth.independent.json, data/apps/io.ente.photos.independent.json, data/apps/jp.pxv.android.json, generate_from_url.py
- Add both Ente apps (Photos + Auth)
- Fix Python script writing invalid JSON (**"null"** instead of **null**)
- Fix apps with missing icons displaying non-existent images
=> Add Ente apps, Fix Python script, Fix missing icons

data/apps/com.aurora.store.nightly.json
=> Fix Aurora Store Nightly

data/apps/org.dolphinemu.dolphinemu.json
=> Fix Dolphin Nightly URL

data/apps/com.synology.dsdrive.json, data/apps/com.synology.projectkailash.json, data/categories.json
see https://github.com/ImranR98/apps.obtainium.imranr.dev/discussions/304#discussioncomment-11136153
=> add two synology apps; replaced the unprecise translation for email client with a more precise one.

data/apps/net.thunderbird.android.beta.json, data/apps/net.thunderbird.android.json
- Updated Thunderbird Beta additional settings to enable "Retain release order from API"
- Added Thunderbird (Stable) to apps.
=> [Apps] Thunderbird Beta and Stable

data/apps/com.mixplorer.beta.json, data/apps/org.thoughtcrime.securesms.json
**MiXplorer**: Closes #325
**Signal**: https://github.com/ImranR98/apps.obtainium.imranr.dev/discussions/282#discussioncomment-11227550
=> Update Signal and MiXplorer

.github/discussion_auto_response.md, .github/workflows/discussion_auto_response.yml, data/strings.json, index.html, script.js
- Adds a GitHub action to automatically respond to new app requests with a link to the app criteria file.
- Adds a link to the app criteria on the modal after clicking the request apps button.
=> Inform users of app criteria

data/apps/org.framasoft.peertube.json
"PeerTube" config was not working.
=> Fix PeerTube config

data/categories.json, data/strings.json
Add japanese translation in strings.json & categories.json
=> Add Japanese Translation

data/apps/com.x8bit.bitwarden.json
The repository used on the Bitwarden config file is not the native app: https://github.com/bitwarden/mobile
Updating it to the native one: https://github.com/bitwarden/android
=> chore: Update Bitwarden to Maintained Repository

data/apps/org.ironfoxoss.ironfox.json
The current config is completely broken, so this fixes it.
=> Fix IronFox

data/apps/app.lawnchair.debug.json
=> Fix Lawnchair (Debug)

data/apps/net.typeblog.shelter.json
Corrected the app ID within the additional settings. It was previously the URL instead of the app ID.
=> Fix Shelter

data/apps/moe.ampersand.app.ci.json
Ampersand is a new tracking app for plural systems.
=> Add Ampersand (CI)

data/apps/eu.artectrex.bunny.json
For some reason the previous APK filters didn't work correctly and I'm not sure why, strange. I've tested these revised filters multiple times to be certain they work.
- Changed APK filters to exact match text using `\b`
=> Refix Bunny Media Editor

data/apps/com.tencent.mm.json
com.tencent.mm (arm64 v8a) currently fails after import with "No APK found", this update fixes that.
=> fix: make obtainum able to find the latest apk of com.tencent.mm 

data/apps/com.donnnno.arcticons.daynight.json, data/apps/com.donnnno.arcticons.json, data/apps/com.donnnno.arcticons.light.json, data/apps/com.donnnno.arcticons.you.json, data/apps/website.leifs.delta.json
- Add Delta's app configs
- Update Arcticons App Categories
- Add "wallpapers"
- Arcticons and Delta provide wallpapers in the apps.
=> Add Delta & Update Arcticons App Categories

data/apps/com.aimp.player.json
Add configuration for AIMP music player, which is generally available through Google Play: https://play.google.com/store/apps/details?id=com.aimp.player
This pull provides configuration for download directly from project's website: https://www.aimp.ru/?do=download&os=android
=> Add AIMP music player

data/categories.json, data/strings.json
* categories.json:
`Sound Recording` -> `录音`
`Video Calling` -> `视频通话`
* strings.json:
`Complex Obtainium Apps` -> `Obtainium 复杂包应用配置`
=> Update Chinese translation

data/apps/app.comaps.json
This PR adds config for CoMaps app https://codeberg.org/comaps/comaps
=> Comaps app

data/apps/com.standardnotes.json
https://github.com/standardnotes/app
APK releases are non-standard on their GitHub
=> Add Standard Notes
